export default {
	organisations: [],
	projects: [],
	emails: [],
	accountStatus: "contributor",
	locale: "en",
	notifications: {
		general_interations: ["email", "push"],
		administrative_messages: ["email", "push"],
		account_login: [],
		smartsplit_blog: [],
		smartsplit_promotions: [],
		partner_promotions: [],
	},
	permissions: { users: [] },
	professional_identity: { public: false, ids: [] },
	collaborators: [],
	contributors: [],
	firstName: "testy",
	lastName: "test",
	artistName: "",
	_id: "48ae33c5-92d7-4e1a-b665-016c5b07cd92",
	__v: 0,
	user_id: "48ae33c5-92d7-4e1a-b665-016c5b07cd92",
	fullName: "testy test",
	rightHolder_id: "48ae33c5-92d7-4e1a-b665-016c5b07cd92",
	email: null,
	$email: { name: "testy test", email: null },
	isAdmin: false,
	isActive: false,
	isDeleted: false,
	canActivate: true,
	id: "48ae33c5-92d7-4e1a-b665-016c5b07cd92",
}
